apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: cicd-k8s-demo-deployment
  labels:
    app: cicd-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-k8s-demo
  template:
    metadata:
      labels:
        app: cicd-k8s-demo  
    spec:
      containers:
        - name: cicd-k8s-demo
          image: smsoooo/cicd-k8s-demo:1.0-fb53226
          ports:
            - containerPort: 8080